#!/usr/bin/env python3
"""Generate the Android launcher icon from docs/icon.svg (the single source).

Writes:
  android/app/src/main/res/drawable/ic_launcher_background.xml   <g id="background">
  android/app/src/main/res/drawable/ic_launcher_foreground.xml   <g id="foreground">
  android/app/src/main/res/drawable/ic_launcher_monochrome.xml   foreground, all black (themed icons)
  docs/icon-preview.png                                           launcher shapes, sizes, themed look

Supports the subset of SVG the icon uses: path, rect (with rx), circle,
ellipse, <g transform="translate(...)">, solid colours and one linear gradient.
Anything else is an error, so the icon can't silently drift from the source.
"""

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/icon.svg"
DRAWABLE = ROOT / "android/app/src/main/res/drawable"
PREVIEW = ROOT / "docs/icon-preview.png"

SVG = "{http://www.w3.org/2000/svg}"
MONO = "#000000"
HEADER = "<!-- Generated by scripts/gen-icon.py from docs/icon.svg. Do not edit. -->"


def num(v):
    return f"{float(v):g}"


def color(c):
    """SVG colour -> Android #AARRGGBB (None for 'none')."""
    if c is None or c == "none":
        return None
    if not re.fullmatch(r"#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}", c):
        sys.exit(f"unsupported colour {c!r}")
    h = c[1:]
    if len(h) == 3:
        h = "".join(ch * 2 for ch in h)
    return "#FF" + h.upper()


def shape_path(el):
    """Path data for a shape element, in SVG syntax (which VectorDrawable accepts)."""
    tag = el.tag.removeprefix(SVG)
    a = {k: float(v) for k, v in el.attrib.items()
         if k in ("x", "y", "width", "height", "rx", "ry", "cx", "cy", "r")}
    if tag == "path":
        return " ".join(el.get("d").split())
    if tag in ("circle", "ellipse"):
        rx = a.get("rx", a.get("r"))
        ry = a.get("ry", a.get("r"))
        cx, cy = a["cx"], a["cy"]
        return (f"M{num(cx - rx)},{num(cy)}a{num(rx)},{num(ry)} 0,1 0,{num(2 * rx)},0"
                f"a{num(rx)},{num(ry)} 0,1 0,{num(-2 * rx)},0Z")
    if tag == "rect":
        x, y, w, h = a.get("x", 0), a.get("y", 0), a["width"], a["height"]
        r = min(a.get("rx", a.get("ry", 0)), w / 2, h / 2)
        if not r:
            return f"M{num(x)},{num(y)}h{num(w)}v{num(h)}h{num(-w)}Z"
        return (f"M{num(x + r)},{num(y)}h{num(w - 2 * r)}a{num(r)},{num(r)} 0,0 1,{num(r)},{num(r)}"
                f"v{num(h - 2 * r)}a{num(r)},{num(r)} 0,0 1,{num(-r)},{num(r)}"
                f"h{num(2 * r - w)}a{num(r)},{num(r)} 0,0 1,{num(-r)},{num(-r)}"
                f"v{num(2 * r - h)}a{num(r)},{num(r)} 0,0 1,{num(r)},{num(-r)}Z")
    sys.exit(f"unsupported element <{tag}>")


def translate(el):
    t = el.get("transform")
    if not t:
        return 0.0, 0.0
    m = re.fullmatch(r"\s*translate\(\s*([-\d.]+)(?:[\s,]+([-\d.]+))?\s*\)\s*", t)
    if not m:
        sys.exit(f"unsupported transform {t!r} (only translate)")
    return float(m.group(1)), float(m.group(2) or 0)


class Converter:
    def __init__(self, root, mono=False):
        self.gradients = {g.get("id"): g for g in root.iter(SVG + "linearGradient")}
        self.mono = mono

    def paint_attrs(self, el, indent):
        out = []
        fill = el.get("fill", "#000")  # SVG's default fill
        if fill and fill.startswith("url("):
            if self.mono:
                out.append(f'android:fillColor="{MONO}"')
            else:
                return out, self.gradient(fill[5:-1], indent)
        elif color(fill):
            out.append(f'android:fillColor="{MONO if self.mono else color(fill)}"')
        stroke = color(el.get("stroke"))
        if stroke:
            out.append(f'android:strokeColor="{MONO if self.mono else stroke}"')
            out.append(f'android:strokeWidth="{num(el.get("stroke-width", 1))}"')
            if el.get("stroke-linecap"):
                out.append(f'android:strokeLineCap="{el.get("stroke-linecap")}"')
            if el.get("stroke-linejoin"):
                out.append(f'android:strokeLineJoin="{el.get("stroke-linejoin")}"')
        return out, None

    def gradient(self, gid, indent):
        g = self.gradients[gid]
        if g.get("gradientUnits") != "userSpaceOnUse":
            sys.exit("gradients must use gradientUnits=userSpaceOnUse")
        pad = " " * indent
        items = "".join(
            f'{pad}        <item android:offset="{num(s.get("offset"))}" android:color="{color(s.get("stop-color"))}" />\n'
            for s in g.iter(SVG + "stop"))
        return (f'{pad}    <aapt:attr name="android:fillColor">\n'
                f'{pad}      <gradient android:type="linear"\n'
                f'{pad}          android:startX="{num(g.get("x1"))}" android:startY="{num(g.get("y1"))}"\n'
                f'{pad}          android:endX="{num(g.get("x2"))}" android:endY="{num(g.get("y2"))}">\n'
                f'{items}{pad}      </gradient>\n'
                f'{pad}    </aapt:attr>\n')

    def children(self, parent, indent):
        out = []
        pad = " " * indent
        for el in parent:
            tag = el.tag.removeprefix(SVG)
            if tag == "g":
                tx, ty = translate(el)
                attrs = "".join(f' android:{k}="{num(v)}"' for k, v in (("translateX", tx), ("translateY", ty)) if v)
                out.append(f"{pad}<group{attrs}>\n")
                out.extend(self.children(el, indent + 4))
                out.append(f"{pad}</group>\n")
                continue
            attrs, gradient = self.paint_attrs(el, indent)
            d = shape_path(el)
            if gradient:
                out.append(f'{pad}<path android:pathData="{d}">\n{gradient}{pad}</path>\n')
            else:
                attr_text = "".join(f"\n{pad}    {a}" for a in attrs)
                out.append(f'{pad}<path{attr_text}\n{pad}    android:pathData="{d}" />\n')
        return out

    def vector(self, group):
        body = "".join(self.children([group], 4))
        aapt = ' xmlns:aapt="http://schemas.android.com/aapt"' if "aapt:attr" in body else ""
        return (f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n'
                f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{aapt}\n'
                '    android:width="108dp"\n    android:height="108dp"\n'
                '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
                f"{body}</vector>\n")


def mono_svg(foreground):
    """The monochrome layer as SVG for the preview, using the same rule as the
    Android layer (every painted fill/stroke becomes one colour)."""
    fg = ET.fromstring(ET.tostring(foreground))
    for el in fg.iter():
        if el.tag == SVG + "g":
            continue
        if el.get("fill", "#000") != "none":
            el.set("fill", "#4A4458")
        if el.get("stroke", "none") != "none":
            el.set("stroke", "#4A4458")
    ET.register_namespace("", SVG[1:-1])
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108">'
            f'<rect width="108" height="108" fill="#E8DEF8"/>{ET.tostring(fg, encoding="unicode")}</svg>')


def render_preview(svg_texts, out):
    import gi
    gi.require_version("Rsvg", "2.0")
    import cairo
    from gi.repository import Rsvg

    surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, 1000, 380 * len(svg_texts))
    cr = cairo.Context(surf)
    cr.set_source_rgb(0.93, 0.93, 0.95)
    cr.paint()
    for row, text in enumerate(svg_texts):
        handle = Rsvg.Handle.new_from_data(text.encode())
        for x, y, size, mask in ((20, 20, 300, "circle"), (350, 20, 300, "squircle"),
                                 (680, 60, 144, "circle"), (840, 60, 96, "squircle"),
                                 (860, 200, 48, "circle")):
            cr.save()
            cr.translate(x, y + row * 380)
            if mask == "circle":
                cr.arc(size / 2, size / 2, size / 2, 0, 6.2832)
            else:
                r = size * 0.3
                cr.arc(r, r, r, 3.1416, 4.7124)
                cr.arc(size - r, r, r, 4.7124, 0)
                cr.arc(size - r, size - r, r, 0, 1.5708)
                cr.arc(r, size - r, r, 1.5708, 3.1416)
                cr.close_path()
            cr.clip()
            s = size / 72.0  # launchers show the centre 72 of the 108 canvas
            cr.translate(-18 * s, -18 * s)
            cr.scale(s, s)
            vp = Rsvg.Rectangle()
            vp.x, vp.y, vp.width, vp.height = 0, 0, 108, 108
            handle.render_document(cr, vp)
            cr.restore()
    surf.write_to_png(str(out))


def main():
    source_text = SOURCE.read_text()
    root = ET.fromstring(source_text)
    groups = {g.get("id"): g for g in root.iter(SVG + "g") if g.get("id")}
    for gid in ("background", "foreground"):
        if gid not in groups:
            sys.exit(f'{SOURCE} needs a <g id="{gid}">')

    outputs = {
        "ic_launcher_background.xml": Converter(root).vector(groups["background"]),
        "ic_launcher_foreground.xml": Converter(root).vector(groups["foreground"]),
        "ic_launcher_monochrome.xml": Converter(root, mono=True).vector(groups["foreground"]),
    }
    for name, text in outputs.items():
        (DRAWABLE / name).write_text(text)
        print(f"wrote {(DRAWABLE / name).relative_to(ROOT)}")

    try:
        render_preview([source_text, mono_svg(groups["foreground"])], PREVIEW)
        print(f"wrote {PREVIEW.relative_to(ROOT)}")
    except Exception as e:  # preview is optional; the drawables are what matter
        print(f"skipped preview (needs librsvg + pycairo): {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
